# Generated by Django 4.2.7 on 2023-11-28 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_post_date_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 13, 30, 18, 914308, tzinfo=datetime.timezone.utc), verbose_name='Дата создания поста'),
        ),
    ]
